package sunda.util;

public class TranslatorFromSundaneseKeyboard {
	public String translate(String ngalagena) {
		switch (ngalagena.toLowerCase()) {
		case "\u1b83":
			return "a";
		case "\u1b84":
			return "i";
		case "\u1b85":
			return "u";
		case "\u1b86":
			return "é";
		case "\u1b87":
			return "o";
		case "\u1b88":
			return "e";
		case "\u1b89":
			return "eu";
		case "\u1b8a":
			return "ka";
		case "\u1b8b":
			return "qa";
		case "\u1b8c":
			return "ga";
		case "\u1b8d":
			return "nga";
		case "\u1b8e":
			return "ca";
		case "\u1b8f":
			return "ja";
		case "\u1b90":
			return "za";
		case "\u1b91":
			return "nya";
		case "\u1b92":
			return "ta";
		case "\u1b93":
			return "da";
		case "\u1b94":
			return "na";
		case "\u1b95":
			return "pa";
		case "\u1b96":
			return "fa";
		case "\u1b97":
			return "va";
		case "\u1b98":
			return "ba";
		case "\u1b99":
			return "ma";
		case "\u1b9a":
			return "ya";
		case "\u1b9b":
			return "ra";
		case "\u1b9c":
			return "la";
		case "\u1b9d":
			return "wa";
		case "\u1b9e":
			return "sa";
		case "\u1b9f":
			return "xa";
		case "\u1ba0":
			return "ha";
		case "\u1bae":
			return "kha";
		case "\u1baf":
			return "sya";
		case "\u1bb0":
			return "0";
		case "\u1bb1":
			return "1";
		case "\u1bb2":
			return "2";
		case "\u1bb3":
			return "3";
		case "\u1bb4":
			return "4";
		case "\u1bb5":
			return "5";
		case "\u1bb6":
			return "6";
		case "\u1bb7":
			return "7";
		case "\u1bb8":
			return "8";
		case "\u1bb9":
			return "9";
		case "pmngkl":
			return "\u1ba1";
		case "pnykra":
			return "\u1ba2";
		case "panyiku":
			return "\u1ba3";
		case "pnghlu":
			return "\u1ba4";
		case "pnyuku":
			return "\u1ba5";
		case "pnle'ng":
			return "\u1ba6";
		case "pnlong":
			return "\u1ba7";
		case "pnglyar":
			return "\u1b81";
		case "_ma":
			return "\u1bac";
		case "_wa":
			return "\u1bad";
		case "":
			return " ";
		case "reu":
			return "\u1bbb";
		case "leu":
			return "\u1bbc";
		case "bha":
			return "\u1bbd";
		case "\u1bbe":
			return "k";
		case "\u1bbf":
			return "m";	
		}
		return ngalagena;	
	}
}